#### 1
GET localhost:8000/mul?a=10&b=10
Authorization: token

#### 2
GET localhost:8000/mul?a=1&b=1
Authorization: token

#### 3
GET localhost:8000/mul?a=12&b=0
Authorization: token

#### 4
GET localhost:8000/mul?a=0&b=10
Authorization: token

#### 5
GET localhost:8000/mul?a=100000&b=10000
Authorization: token